#######
# Compiled from data/test/functions/files.mcscript
# to .//data/test/functions/files/function.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/test/functions/files.mcscript
say this is the function