#######
# Compiled from data/test/functions/files.mcscript
# to .//data/test/functions/files/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######


function test:files/function
say this is the main