#######
# Compiled from data/test/functions/load.mcscript
# to .//data/test/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

scoreboard objectives add mcscript_raycast dummy
scoreboard objectives add motionX dummy
scoreboard objectives add motionZ dummy
