#######
# Compiled from data/test/functions/click.mcscript
# to data/test/functions/mcscript/raycast1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[distance=5..] run particle flame

execute if block ~ 54 ~ gray_stained_glass run tag @s add mcscriptStop

scoreboard players add raycast1 mcscript_raycast 1
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run tag @s add mcscriptStop
execute positioned ^ ^ ^1 if entity @s[tag=!mcscriptStop] if block ~ ~ ~ air if score raycast1 mcscript_raycast matches ..100 run function test:mcscript/raycast1
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run scoreboard players set @e[tag=target] motionX 0
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run scoreboard players set @e[tag=target] motionZ 0
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute align x positioned ~0.5 ~ ~0.7 run scoreboard players remove @e[tag=target,distance=..0.6] motionZ 1
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute align x positioned ~0.5 ~ ~-0.7 run scoreboard players add @e[tag=target,distance=..0.6] motionZ 1
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute align z positioned ~0.7 ~ ~0.5 run scoreboard players remove @e[tag=target,distance=..0.6] motionX 1
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute align z positioned ~-0.7 ~ ~0.5 run scoreboard players add @e[tag=target,distance=..0.6] motionX 1
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute as @e[tag=target,distance=..5] run execute store result entity @s Motion[0] double 0.1 run scoreboard players get @s motionX 
execute if score raycast1 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run execute positioned ^ ^ ^-1 run execute as @e[tag=target,distance=..5] run execute store result entity @s Motion[2] double 0.1 run scoreboard players get @s motionZ 
tag @s[tag=mcscriptStop] remove mcscriptStop
