#######
# Compiled from data/test/functions/click.mcscript
# to .//data/test/functions/click.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast1 mcscript_raycast 0
execute positioned ~ ~1 ~ run function test:mcscript/raycast1
