#######
# Compiled from data/test/functions/main.mcscript
# to .//data/test/functions/player.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/test/functions/main.mcscript

fill ~2 ~2 ~2 ~-2 ~-2 ~-2 air replace barrier
execute if entity @s[tag=isWall] run execute if block ~ ~-1 ~ air run setblock ~ ~-1 ~ barrier
execute if entity @s[tag=isWall] run tag @s remove isWall

execute if block ~1 ~ ~ pink_concrete run tag @s add isWall
execute if block ~-1 ~ ~ pink_concrete run tag @s add isWall
execute if block ~ ~ ~1 pink_concrete run tag @s add isWall
execute if block ~ ~ ~-1 pink_concrete run tag @s add isWall
execute if block ~1 ~1 ~ pink_concrete run tag @s add isWall
execute if block ~-1 ~1 ~ pink_concrete run tag @s add isWall
execute if block ~ ~1 ~1 pink_concrete run tag @s add isWall
execute if block ~ ~1 ~-1 pink_concrete run tag @s add isWall
execute if block ~ ~-1 ~ orange_concrete run effect give @s minecraft:speed 1 5 true

execute if block ~ ~-1 ~ lime_concrete run effect give @s minecraft:jump_boost 1 3 true

execute if score @s click matches 1.. run function test:click
execute if score @s click matches 1.. run scoreboard players set @s click 0
