#######
# Compiled from data/test/functions/summon.mcscript
# to .//data/test/functions/summon.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz run summon boat ~0.5 ~0.5 ~0.5 {Tags:[target],NoGravity:1b,Invulnerable:1b,Type:"oak",Passengers:[{id:"minecraft:turtle",Silent:1b,Invulnerable:1b,PersistenceRequired:1b,NoAI:1b},{id:"minecraft:turtle",Silent:1b,Invulnerable:1b,PersistenceRequired:1b,NoAI:1b}]}